apiVersion: choreo.dev/v1alpha1
kind: Service
metadata:
  name: flask-backend-service
spec:
  endpoints:
    - path: /api/send-mail
      method: POST
      backend: flask-backend
      type: http
      secured: false
      request:
        contentType: application/json
      response:
        contentType: application/json
