services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$FLASK_RUN_PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_USERNAME
        value: votre_email@gmail.com
      - key: MAIL_PASSWORD
        value: mot_de_passe
